import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
    return {
        rules: {
            userAgent: "*",
            allow: "/",
            disallow: [
                "/api/",
                "/dashboard",
                "/dashboard/",
                "/settings",
                "/settings/",
                "/sessions",
                "/sessions/",
                "/invoices",
                "/invoices/",
                "/reports",
                "/reports/",
                "/inventory",
                "/inventory/",
                "/expenses",
                "/expenses/",
                "/facilities",
                "/facilities/",
                "/fish-types",
                "/fish-types/",
                "/fish-buybacks",
                "/fish-buybacks/",
                "/customers",
                "/customers/",
                "/pricing",
                "/pricing/",
                "/products",
                "/products/",
                "/admin",
                "/admin/",
                "/activity",
                "/activity/",
                "/verify-phone",
                "/prototype",
                "/prototype/",
                "/403",
            ],
        },
        sitemap: "https://quanlihocau.com/sitemap.xml",
    };
}
