import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
    const disallowedPaths = [
        "/api/",
        "/dashboard",
        "/dashboard/",
        "/settings",
        "/settings/",
        "/sessions",
        "/sessions/",
        "/invoices",
        "/invoices/",
        "/reports",
        "/reports/",
        "/inventory",
        "/inventory/",
        "/expenses",
        "/expenses/",
        "/facilities",
        "/facilities/",
        "/fish-types",
        "/fish-types/",
        "/fish-buybacks",
        "/fish-buybacks/",
        "/customers",
        "/customers/",
        "/pricing",
        "/pricing/",
        "/products",
        "/products/",
        "/admin",
        "/admin/",
        "/activity",
        "/activity/",
        "/verify-phone",
        "/prototype",
        "/prototype/",
        "/403",
    ];

    return {
        rules: [
            {
                userAgent: "*",
                allow: "/",
                disallow: disallowedPaths,
            },
            {
                userAgent: "Googlebot",
                allow: [
                    "/",
                    "/bang-gia",
                    "/thiet-bi-may-in",
                    "/dieu-khoan",
                    "/chinh-sach-bao-mat",
                    "/login",
                    "/register",
                    "/opengraph-image",
                    "/icons/",
                ],
                disallow: disallowedPaths,
            },
            {
                userAgent: [
                    "GPTBot",
                    "Google-Extended",
                    "PerplexityBot",
                    "ClaudeBot",
                    "Applebot-Extended",
                ],
                allow: [
                    "/",
                    "/bang-gia",
                    "/thiet-bi-may-in",
                    "/dieu-khoan",
                    "/chinh-sach-bao-mat",
                ],
                disallow: disallowedPaths,
            },
        ],
        sitemap: "https://quanlihocau.com/sitemap.xml",
        host: "https://quanlihocau.com",
    };
}
